### ISSUE TITLE
Bad Performance vs. httpclient library 

### ISSUE THREAD

**Issue by VanitySoft** [Kong/unirest-java#124]
Ok, so unirest-java performs significantly bad vs. HttpClient 4.3.x. i've been testing both libraries extensively performing a HTTPS Get request to our hosted app on mashape returning a 14MB response. unirest-java averages 8.4 seconds, vs. httpclient(default) 3.5 seconds..

**Comment by ryber** [comment]
Unirest is never going to be as fast as HttpClient since it simply wraps it. So It's always going to be HttpClient +

It also does things in a generic easy way to simplify HttpClient which means it's not going to hit every edge case as well. Still, the new version does several optimizations. You can try it out and if you have some specific reproducible scenarios I can look at those
