### ISSUE TITLE
How can I create multiple instances of Unirest?

### ISSUE THREAD

**Issue by miso-belica** [Kong/unirest-java#145]
Hi,
is there any chance that I can create multiple instances of unirest object? I would like to have multiple unirest objects with different configuration (timeouts, default headers, ...) in the application. I think this is not possible now. Is there any chance to have it in the future or is there some workaround?

Unirest seems like great library, but I can't use it because I have many different scenarios with different configuration in application and I don't want they interfere each other.

Thanks for the response in advance :)

**Comment by MiErnst** [comment]
I would also like to have the option for multiple configurations, the currently used static configuration of the client looks a bit shortsighted. I think a lot of applications would like to access multiple resources and not each resource should have the same configuration e.g. for socket connection timeouts. I would also like to prefer a more instance based client instead of the whole static calls. Maybe there could be an option to get an own managed instance via something like `Unirest.getClient()` on which I can set my own configuration which is currently only possible via the static methods.

**Comment by sithu** [comment]
+1

**Comment by johnnorton** [comment]
+1

**Comment by csokol** [comment]
+1 

This feature would be really useful for me, also. Right now I need to integrate with multiple API's and defining different timeouts for each one of them is impossible.

**Comment by fermin-silva** [comment]
Static calls, while convenient for quick scripts, are difficult for unit testing, because it's impossible to inject a mocked instance into the object to be tested.
Let the user decide if they want a singleton instance or multiple of them

**Comment by rillgen** [comment]
+1

**Comment by racoma** [comment]
+1

**Comment by jtburke** [comment]
👍

**Comment by Flemingjp** [comment]
+1

**Comment by tjshefbina** [comment]
me too 💯

**Comment by bigkahuna1uk** [comment]
+1

**Comment by rfpe** [comment]
+1

**Comment by aldosuwandi** [comment]
:+1:

**Comment by josoriorios** [comment]
+1

**Comment by yurigava** [comment]
+1

**Comment by findhamid** [comment]
+1

**Comment by aggregat4** [comment]
+1

**Comment by AxiFive** [comment]
+1
I want to run parallel threads and call rest api through unirest with different proxies.

**Comment by comschmid** [comment]
+1

**Comment by josueeduardo** [comment]
Trying to add this feature to a fork [here](https://github.com/josueeduardo/rest-client)

**Comment by alicanalbayrak** [comment]
+1

**Comment by itsdax** [comment]
+1

**Comment by VijayKumarMidde** [comment]
+1

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
