### ISSUE TITLE
BasicAuth

### ISSUE THREAD

**Issue by nijikokun** [Kong/unirest-java#16]
To be consistent with the other libraries should be `auth`

**Comment by varra4u** [comment]
I think basicAuth() holds good, since we are talking about specific authentication mechanism  (i.e Basic Authentication) here in Unirest with basicAuth().

We know that JEE and some other third party libraries do use auth() as the method name since they do accept any kind of authentication mechanism like given below:

1) BASIC
2) DIGEST
3) FORM
4) CLIENT-CERT, or 
5) Any vendor-specific authentication scheme.

Hope my answer reveals the secret behind the naming convention for basicAuth().

**Comment by RJPalombo** [comment]
I see the PHP lib supports other auth types. Will this lib only support basic? The PHP also shows the more generic "auth" method, then as a parameter you can specify what type.

**Comment by ryber** [comment]
We should look in the future to support specific headers for various token types (like Bearer tokens) but for how the header methods support this just file
