### ISSUE TITLE
_ not allowed in hostname?

### ISSUE THREAD

**Issue by jessica-pixvana** [Kong/unirest-java#170]
```
final String webPage = "https://api_demo.hybrik.com/v1/login";
final HttpResponse<JsonNode> response = Unirest.post(webPage)
```

```
java.lang.RuntimeException: java.net.URISyntaxException: Illegal character in hostname at index 11: https://api_demo.hybrik.com/v1/login?

```

**Comment by dim-s** [comment]
`_` is not valid symbol for domains and subdomains!

**Comment by lhchingit** [comment]
Hi,
It is normal while using RestTemplate (provided by Spring Boot) or OkHttp.

**Comment by sarath21** [comment]
It does work in org.apache.http.impl.client.CloseableHttpClient. Is there any specific reason why its not supported here?

In com.mashape.unirest.http.HttpClientHelper prepareRequest method, i see the following content. Because this using uri, its failing. Version i'm using is 1.4.9.

`
URL url = new URL(request.getUrl());
URI uri = new URI(url.getProtocol(), url.getUserInfo(), url.getHost(), url.getPort(), URLDecoder.decode(url.getPath(), "UTF-8"), "", url.getRef());
			urlToRequest = uri.toURL().toString();


`

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
