### ISSUE TITLE
Add Option For Shaded Fat Jar

### ISSUE THREAD

**Issue by ryber** [Kong/unirest-java#272]
Add an option for a shaded jar

**Comment by davidghiurco** [comment]
Could I also request that this dependency be shaded? httpclient is a widely used package, I typically have at least 4 different versions of it from transitive dependencies in my projects, and sometimes they produce class-loading conflicts when newer dependencies (other than unirest) are upgraded and they use a newer httpclient dependency ......

I've found that most libraries nowadays shade things dependency libraries such as guava/jackson/httpclient in order to allow maximum flexibility to users to use what dependencies they want without classpath headaches.

**Comment by ryber** [comment]
I'd actually be open to doing that with the current version @davidghiurco. I need to test some things out though, there are lots of folks who inject custom Apache Http Clients into Unirest. Need to see how well that works when Unirest is using a shaded version?

**Comment by davidghiurco** [comment]
@ryber The problem I'm currently facing is unirest-java uses httpclient 4.5.8 (latest), but I also have wiremock-jre8 which uses httpclient 4.5.6. The builders for configurations are different in these two versions, which means compile-time NoClassDef due to classpath conflicts

The solution was for me to use wiremock-jre8-standalone which shades all of its dependencies: netty, httpclient, guava. 

It would be nice if that option was reciprocal from unirest-java as well.

**Comment by davidghiurco** [comment]
> I'd actually be open to doing that with the current version @davidghiurco. I need to test some things out though, there are lots of folks who inject custom Apache Http Clients into Unirest. Need to see how well that works when Unirest is using a shaded version?

I'm not a veteran unirest user, are you referring to:

     Unirest.config()
            .httpClient(myClient)
            .asyncClient(myAsyncClient)

from https://github.com/Kong/unirest-java#setting-custom-apache-client ? 

If yes, I don't think this byte-level package relocation using things like the maven shade plugin relocation feature has any impact on ability to do this.

**Comment by davidghiurco** [comment]
> I'd actually be open to doing that with the current version @davidghiurco. I need to test some things out though, there are lots of folks who inject custom Apache Http Clients into Unirest. Need to see how well that works when Unirest is using a shaded version?

After reading your response one more time, I think you misunderstood my request a bit. I'm not saying used a shaded version of the httpclient dependency, but rather shade (a.k.a. relocate) that dependency into a whole seperate "unirest-java-standalone" i.e. fat-jar artifact.

**Comment by ryber** [comment]
Yea, I get what your saying. I'm familiar with using fat-jars as deployable and using them when the internals are hidden. Just wasn't sure what it looked like when those shaded dependencies leaked of the interfaces like they do in Unirest. I've managed to clean up most of it but there are still a few places.

At the very least I want to be able to document what classloader issues a user might experience if they're using a different version of Apache than the shaded dependency.

Let me ask this, do you see a strong reason to offer both a shaded and traditional Unirest? Why not just always offer the shaded one?

**Comment by davidghiurco** [comment]
> Let me ask this, do you see a strong reason to offer both a shaded and traditional Unirest? Why not just always offer the shaded one?

There are 3 reasons to offer both (i.e. to not use the shaded one all the time), that I can think of. 

1) Shading - a jargon term for relocating the packages in the compiled bytecode of a library, was a solution to a rather annoying problem: class-loading conflicts when you have competing versions of the same library in the same classpath.
Thus, shading should only be used when you have such a scenario. Otherwise, you're solving a problem that doesn't exist.

2) Shading all dependencies of a library means that a library which is 200 kB, could possibly become 50 MB when all of its dependencies are shaded in to the fat-jar. Imagine I add a dependency on a library and only use 1 class from the whole library. When I look at the size of my built project artifact, I would be surprised to find that 1 small dependency increased the artifact size by 50 MB. In a world of containerized deployments, small artifact sizes are desirable. 

3) Shading effectively makes the library not have any dependencies. This means that when someone looks at the POM of a shaded dependency, they will not be able to see what libraries that dependency actually depends on.

**Comment by ryber** [comment]
I'm changing this issue to just the fat-jar issue to preserve the conversation

**Comment by ryber** [comment]
Huh, it failed to deploy
```
[INFO] [ERROR] Repository "comkonghq-1015" failures
[INFO] [ERROR]   Rule "sources-staging" failures
[INFO] [ERROR]     * Illegal POM: /com/konghq/unirest-java-parent/2.3.03/unirest-java-parent-2.3.03-standalone.pom only whitespace content allowed before start tag and not P (position: START_DOCUMENT seen P... @1:1) 
[INFO] [ERROR]   Rule "pom-staging" failures
[INFO] [ERROR]     * Invalid POM: /com/konghq/unirest-java-parent/2.3.03/unirest-java-parent-2.3.03-standalone.pom: Parsing Error: only whitespace content allowed before start tag and not P (position: START_DOCUMENT seen P... @1:1) 
[INFO] [ERROR]   Rule "javadoc-staging" failures
[INFO] [ERROR]     * Illegal POM: /com/konghq/unirest-java-parent/2.3.03/unirest-java-parent-2.3.03-standalone.pom only whitespace content allowed before start tag and not P (position: START_DOCUMENT seen P... @1:1) 
```

I don't even see the standalone pom in the target. 
```
~/Developer/unirest-java/unirest/target$ ls
apidocs					javadoc-bundle-options			unirest-java-2.3.03-sources.jar
checkstyle-checker.xml			maven-archiver				unirest-java-2.3.03-sources.jar.asc
checkstyle-result.xml			maven-status				unirest-java-2.3.03-standalone.jar
checkstyle-suppressions.xml		site					unirest-java-2.3.03-standalone.jar.asc
classes					surefire-reports			unirest-java-2.3.03.jar
generated-sources			test-classes				unirest-java-2.3.03.jar.asc
generated-test-sources			unirest-java-2.3.03-javadoc.jar		unirest-java-2.3.03.pom
jacoco.exec				unirest-java-2.3.03-javadoc.jar.asc	unirest-java-2.3.03.pom.asc
```

any idea?

**Comment by ryber** [comment]
I opened a ticket with Sonatype https://issues.sonatype.org/browse/MVNCENTRAL-4898

**Comment by davidghiurco** [comment]
> I opened a ticket with Sonatype https://issues.sonatype.org/browse/MVNCENTRAL-4898

https://stackoverflow.com/questions/13929633/maven-install-error-only-whitespace-content-allowed-before-start-tag-and-not

Never seen that before, but it sounds like it may just be some corrupt ~/.m2/ file in your local repository when you deploy. I always do clean builds i.e. clean package, clean install, clean deploy etc and have never had this issue.

**Comment by ryber** [comment]
@davidghiurco have you deployed fat-jars to maven central though? The Sonatype staging server we use has a bunch of extra validation you don't normally get from a private nexus or artifactory

**Comment by davidghiurco** [comment]
> @davidghiurco have you deployed fat-jars to maven central though? The Sonatype staging server we use has a bunch of extra validation you don't normally get from a private nexus or artifactory

Alas, I have not. I've only used private Nexus and Artifactory, just like you mentioned. 

I do know, however, that it is possible. Wiremock, for example, does it: 
http://wiremock.org/docs/download-and-installation/
https://mvnrepository.com/artifact/com.github.tomakehurst/wiremock-standalone

**Comment by ryber** [comment]
So yea, the unirest-java-parent-2.3.04-SNAPSHOT-standalone.pom that is generated is corrupt (or at not valid XML) . Wiremock produces this:
http://central.maven.org/maven2/com/github/tomakehurst/wiremock-standalone/2.23.2/wiremock-standalone-2.23.2.pom

I get this stuff (mostly unknown chars):
<img width="429" alt="maven" src="https://user-images.githubusercontent.com/145359/59158894-e0022b00-8a86-11e9-8b37-01154ff3fa0a.png">

**Comment by ryber** [comment]
What do you get if you do a mvn package @davidghiurco ?

I'm on mvn 3.6.1

**Comment by davidghiurco** [comment]
I am likewise on mvn 3.6.1

               <createDependencyReducedPom>false</createDependencyReducedPom>

I included this line in the pull request with the shade plugin configuration. Evidently, wiremock has it set to true. I personally prefer to know what libraries a dependency uses, even if they're shaded into the dependency itself. My expectation from reading the maven-shade-plugin documentation would be that if this is set to false, the dependencies listed in the normal pom would also be listed in the standalone pom. 

I think the first thing to try is to set that property to "true" instead. If that works, great. 
In any case, this seems like a bug with the maven-shade-plugin which I'm really surprised about ...


Where exactly did you find that standalone pom? I can't seem to find it in my target:
![image](https://user-images.githubusercontent.com/9147386/59161241-cb815b00-8aa5-11e9-8132-8cf260e0e2ec.png)

**Comment by ryber** [comment]
Oh I guess I just get it in the parent project

**Comment by davidghiurco** [comment]
> Oh I guess I just get it in the parent project

Oh! That actually helps a lot. I know why. I will push a PR with fix.

**Comment by ryber** [comment]
2.3.05 is released! Thanks a lot @davidghiurco
