### ISSUE TITLE
Get Body as String after mapping to Object

### ISSUE THREAD

**Issue by wildfiregt** [Kong/unirest-java#278]
Hi

Would be nice to add a second method (ex getRawBody() ) in HttpResponse interface returning the original response String Body even if we use .asObject() method for mapping.

Thanks for reviewing this option

**Comment by ryber** [comment]
The original string is kept in the parsing exception if that gets captured. Is that the use case you're looking for? Or you just want to see it? 

My main concern with always keeping it around is that I'd like to change the ObjectMappers to work off of the InputStream, rather than the string, which would improve performance and wouldn't chew up so much memory. Keeping the string around all the time is kind of counter to that.

**Comment by wildfiregt** [comment]
I want to log every response I get from my requests. As for now, I'm getting the responses as Strings, log them, and them parse them manually via Gson. 
Having to catch a parsing exception everytime is not ideal

**Comment by ryber** [comment]
OK so I think you are using an older version of Unirest. The newest version no longer throws up on parsing errors but rather captures the error as well as the original string. There are also some handler consumers that can make the entire thing a little cleaner:

```java
Unirest.get("http://somewhere")
                .asObject(RequestCapture.class)
                .ifSuccess(response -> someSuccessMethod(response))
                .ifFailure(response -> {
                    log.error("Oh No! Status" + response.getStatus());
                    response.getParsingError().ifPresent(e -> {
                        log.error("Parsing Exception: ", e);
                        log.error("Original body: " + e.getOriginalBody());
                    });
                })
```
Check out the upgrade guide:
https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md

and the help (still incomplete but getting better:
http://kong.github.io/unirest-java/

Also we also now have a packaged GSON (as well as Jackson) Object Mapper so you don't need to roll your own if you don't want to: https://mvnrepository.com/artifact/com.konghq/unirest-object-mappers-gson

**Comment by ryber** [comment]
going to go ahead and close this as I believe we already have a solution for the core issue

**Comment by ngueno** [comment]
@ryber actually I am facing the same issue. we are returning a 400 response from our service, we return the following body:

```
{
  "timestamp": 1512713804164,
  "status": 400,
  "error": "16542",
  "message": "Your balance check is not configured",
  "path": "/..."
}
```

When we use `asObject(Balance.class)` to call our balance endpoint, we do receive our `Balance` object as expected when there is a 200 response.

The problem occurs when we return the error body, in this case there is nothing on `response.getParsingError()` since it is not related to parsing, but an error mapping to inform our what is going on, and provide a chance to him handle it accordingly.
For this case, we receive the `Balance` response but all properties are empty. 

I have tried to recover the original body using an interceptor:

```
            @Override
            public void onResponse(HttpResponse<?> response, HttpRequestSummary request, Config config) {
                response.ifFailure(ErrorDetail.class, r -> {
                    ErrorDetail errorDetail = r.getBody();
                    throw new JunoApiException(errorDetail);
                });
            }
```

But also it is impossible to recover the original payload, all properties are returning null.
It would be great to have the original response JSON available, this way we should be able to instead of get the already parsed object (which is not useful), we will be able to map it to our `ErrorDetail` class

**Comment by ngueno** [comment]
@ryber  I am available to help with this feature if needed, this approach will be interesting to enable our customers to catch our exception, check the error and handle it.

**Comment by ryber** [comment]
The main problem is that the default object mapper is pretty laissez-faire about the JSON in the response, It's set to only map what it can by default and unless the class itself marks any fields as required then it's just going to nothing. So the mapper thinks it's successful, there just were no matching fields.

This can be handled in a few ways out of the box without modifications by getting strict with your Json Object mapper. By default Unirest uses GSON and you can add a field or two with @JsonRequired, Jackson has something similar.

I'm not opposed to doing something more to keep it around, perhaps as a config option. Where it gets complicated is that I have a goal of adding InputStream support to the object mappers so we don't have to read the entire response into memory at once for streaming responses. So anything done should have that in mind.

**Comment by ngueno** [comment]
@ryber I have tried to set Jackson to fail on unknown properties, we have customized the serialization and deserialization as the following:

 ```
       Unirest.config().setObjectMapper(new ObjectMapper() {

            @Override
            public String writeValue(Object value) {
                try {
                    return JacksonUtils.getObjectMapper().writeValueAsString(value);
                } catch (JsonProcessingException e) {
                    throw new JunoApiException(e);
                }
            }

            @Override
            public <T> T readValue(String value, Class<T> valueType) {
                try {
                    return JacksonUtils.getObjectMapper().readValue(value, valueType);
                } catch (JsonProcessingException e) {
                    throw new JunoApiException(e);
                }
            }

            @Override
            public <T> T readValue(String value, GenericType<T> genericType) {
                try {
                    return JacksonUtils.getObjectMapper().readValue(value, new TypeReference<T>() {

                        @Override
                        public Type getType() {
                            return genericType.getType();
                        }
                    });
                } catch (JsonProcessingException e) {
                    throw new JunoApiException(e);
                }
            }
        });
```
The `ObjectMapper` is also configured as the following in our `JacksonUtils`:
    
```
    public static ObjectMapper getObjectMapper() {
        if (mapper == null) {
            // @formatter:off
            mapper = Jackson2ObjectMapperBuilder.json()
                    .modules(
                            new ParameterNamesModule(),
                            new Jdk8Module(),
                            new JavaTimeModule(),
                            new Jackson2HalModule()
                    )
                    .failOnUnknownProperties(true)
                    .serializationInclusion(Include.NON_NULL)
                    .build();
            // @formatter:on
        }

        return mapper;
    }
```

Unfortunately it had no effect, properties are deserialized as null on our object, without parsing errors :(

**Comment by ryber** [comment]
Just for my own sanity I wrote a couple of tests showing configuring for failure on unknown properties:

https://github.com/Kong/unirest-java/commit/493b17395369e6eb5ae29318c6420eb046af9591

**Comment by cw-dimedis** [comment]
We have the exact same issue as the original poster. We would like to log the raw body of the response (e.g. for debugging purposes), even if the request and object mapping was successful. But there's no way to access it after using `asObject()`.

Our workaround is using `asString()` for the log output and then do the object mapping separately with Jackson. It's not a big deal, but it's a bit sad we cannot use Unirest's in-built object mapping feature only because of this.

**Comment by ryber** [comment]
@cw-dimedis, the jackson (or any) object mapper gets passed a string. You can override that method and put your logger there:

```
JacksonObjectMapper om = new JacksonObjectMapper(){
        @Override
        public <T> T readValue(String value, Class<T> valueType) {
            logger.info("Body: " + value)
            return super.readValue(value, valueType);
        }
    };
```

**Comment by ryber** [comment]
also, to anyone else following this. Unirest now keeps the body around on failure starting in 3.4.04 https://github.com/Kong/unirest-java/blob/master/CHANGELOG.md#3404

**Comment by gustahrodrigues** [comment]
Hi @ryber, I'm facing the same issue here. I've realized the improvements made to have `rawBody` around, but how can I get it 
 since `ObjectResponse.java` is not public ([reference](https://github.com/Kong/unirest-java/commit/c1eec1ac14e2bbc89fb169f785b2fb352c2bf35e#diff-e0bc3621929fee6710003e1b7505c3e7R32))?

```java
final HttpResponse<MyObject> response = Unirest.post(url)
      .body(requestBody)
      .asObject(MyObject.class);
       
final ObjectResponse rawResponse = (ObjectResponse) response; // Fail to import it
final String originalBody = rawResponse.getRawBody();

```

By using `getParsingError().get().getOriginalBody()` is not enough for me, since sometimes I don't have a parsing error, but I need the original body tough.

**Comment by ryber** [comment]
The original body is available though the mapError method you can map the error to String.class

It's only kept around in the event of a non-200 or parsing error. Does that work for you?

Keeping or even knowing the original body is kind of a tricky thing. We can't just always do it because there are streaming responses where doing so would result in OOM.in the future we plan on doing even more with streaming and working more closely with the object mapper in which case the input stream will be completely or partially consumed by Jackson or Gson or whatever.

**Comment by gustahrodrigues** [comment]
It works like a charm! Thank you!

Following my code to be used as reference for future readers:

```java
final HttpResponse<MyObject> response = Unirest.post(url)
      .body(requestBody)
      .asObject(MyObject.class);
       
final String originalBody = response.mapError(String.class);
```
