### ISSUE TITLE
FeatureRequest: Simple way of getting the response as a byte array

### ISSUE THREAD

**Issue by Chaiavi** [Kong/unirest-java#297]
**Is your feature request related to a problem? Please describe.**
Many online objects are binary and not textual, thus getting a byte array as the response is very important.

Getting the response as a file is done easily, but involves IO which is a problem for many users.
The only way to get the response as binary is to use the .thenConsume lmbda function which is ok, but is much less convenient IMHO.

**Describe the solution you'd like**
I suggest adding asBytes() method (like asString, asJson etc which exist)
I understand that this is a helper method only, but it will make the API much easier

**Comment by ryber** [comment]
Once upon a time the original unirest had a ```asBinary``` method which returned a InputStream. The problem was that the InputStream was a copy of the original one and folk would run out of memory attempting to get huge files, so it was essentially replaced with the thenConsume method that let you get to the stream directly (there are also some complexities with when it gets closed and interactions with Apache under the covers)

Anyway, I like the idea of just returning a byte[] if you want the raw bytes, at least that doesn't give the illusion that you aren't going to need to deal with having all the bytes in memory at once.

**Comment by ryber** [comment]
This is released as 2.4.00 https://repo.maven.apache.org/maven2/com/konghq/unirest-java/2.4.00/

**Comment by ryber** [comment]
see https://github.com/Kong/unirest-java/blob/master/unirest/src/test/java/BehaviorTests/AsBytesTest.java

**Comment by Chaiavi** [comment]
Thanks @ryber
