### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.http.ssl.SSLContexts 

### ISSUE THREAD

**Issue by dpalic** [Kong/unirest-java#312]
HttpResponse<JsonNode> lResponse = Unirest.get(URL).queryString(PARAM_URL, lDomain)
				.queryString(PARAM_MATCH_TYPE, lMatchType).queryString(PARAM_OUTPUT, lOutputFormat).asJson();

this is the full code I am using of UniRest right now.
My URL is not even https it is http. This issue seems to be the same issue as #221 

in my classpath I have:

![image](https://user-images.githubusercontent.com/1399203/67623721-dfe1ac80-f828-11e9-9cbb-bbbd41330f42.png)

**Comment by dpalic** [comment]
afaik found the issue.
Your lib requires httpcore 4.4.1 and you exclude it from dependencies which is not good
https://github.com/Kong/unirest-java/blob/44cc5cbc67f4817f12d0259a6c2b142fe1baa007/unirest/pom.xml#L47

afaik you shall add it as dependency with a version range, e.g. like this
<groupId>org.apache.httpcomponents</groupId>
<artifactId>httpcore</artifactId>
<version>[4.4.1,4.5)</version>

**Comment by ryber** [comment]
It's only excluded from the async client because it's also included from the "regular" http client which uses a newer version than the async client uses and is dependent on newer methods (it cannot use the older one)

```
[INFO] com.konghq:unirest-java:jar:3.1.03-SNAPSHOT
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.5.9:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.11:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  \- commons-codec:commons-codec:jar:1.11:compile
[INFO] +- org.apache.httpcomponents:httpmime:jar:4.5.9:compile
[INFO] +- org.apache.httpcomponents:httpasyncclient:jar:4.1.4:compile
[INFO] |  \- org.apache.httpcomponents:httpcore-nio:jar:4.4.10:compile
[INFO] \- com.google.code.gson:gson:jar:2.8.5:compile
```

I can see from your list of depenencies that you are pulling in some older versions of httpclient than unirest uses. This can cause issues. The apache project isn't th ebest about backwards compatibility.

There is a fat jar version of Unirest that you can use that eliminates the conflicts with other dependencies (at the expense of fatness)

**Comment by ryber** [comment]
Oh I also just noticed you are using an ancient version of unirest (1.4.9)

**Comment by ryber** [comment]
Closing this as it looks like upgrading will resolve the issue
