### ISSUE TITLE
encoding of the path does not escape spaces

### ISSUE THREAD

**Issue by Jebusito** [Kong/unirest-java#319]
Migrated from a really old Unirest version (1.4.10).
On that version, it escaped the spaces as %20, but now it doesn't so it seems like a regression.

Exception given:
Caused by: java.net.URISyntaxException: Illegal character in path at index 50: http://192.168.1.13:8000/v1/archivo/demo/expresion interes.pdf

**To reproduce**
GetRequest request = Unirest.get(any given url with a space);

**Expected behavior**
The url should be encoded to
http://192.168.1.13:8000/v1/archivo/demo/expresion%20interes.pdf

**Environmental Data:**
 - Java 1.8.0_221b-11
 - Unirest Version [3.1.04]

**Comment by ryber** [comment]
This will be released, probably tomorrow. 

note that this is a pretty limited fix for raw paths containing spaces specifically, Now that I think of it I'll go back and add tabs as well, but when dealing with a raw URL at some point it's up to the user to make sure they are passing in a proper URL (technically a URL with a space is not a valid URL). We cannot just url-encode the entire URL because that would itself make it invalid.
