### ISSUE TITLE
unirest-java 3.14.3 POM does not contain Apache HTTP Client dependency anymore

### ISSUE THREAD

**Issue by timomeinen** [Kong/unirest-java#474]
It seems there was a deployment issue with the latest release:

https://search.maven.org/artifact/com.konghq/unirest-java/3.14.3/jar

The published pom.xml does not contain dependency to org.apache.httpcomponents:httpclient anymore.

**Comment by haroon-sheikh** [comment]
I was just about to report the same. We're seeing a similar issue `java.lang.NoClassDefFoundError: org/apache/http/nio/protocol/HttpAsyncResponseConsumer` 

It could possible due to an update to the maven-shade-plugin https://github.com/Kong/unirest-java/commit/11cea491a96d7f975680cae2c4509396eaa18279

**Comment by mgerlach** [comment]
Same here.

Also jackson is missing when using unirest-objectmapper-jackson.

The packaged unirest-java and unirest-objectmapper-jackson pom.xml files you get from Maven Central are different from  the ones in this repo:

https://github.com/Kong/unirest-java/blob/v3.14.3/unirest/pom.xml has the httpcomponents dependencies which are missing in the package from Maven Central
https://github.com/Kong/unirest-java/blob/v3.14.3/object-mapper-jackson/pom.xml has the jackson dependency which is missing in the package from Maven Central

**Comment by timomeinen** [comment]
@ryber We use Renovate to keep up-to-date and for minor releases like this one we simply automerge.

**Comment by timomeinen** [comment]
Thanks @ryber. Works again.
