### ISSUE TITLE
[Feature Request] Jackson JSON library

### ISSUE THREAD

**Issue by blowupyourchains** [Kong/unirest-java#74]
make json lib configurable or change to jackson library

**Comment by dewos** [comment]
#83

**Comment by djKianoosh** [comment]
I believe #83 is different from this request. If I read the code right, that PR is more about mapping the entire json response into a specific object.

I think users would like to get an arbitrary object _within_ a complex json response as a particular type. So instead of :
`JSONArray array = jsonResponse.getBody().getObject().getJSONObject("user").getJSONArray("likes")`

A user may want to map "user.likes" directly to a `List<Like>` list of Like of objects. (totally made up example, but I think it makes sense).

**Comment by dewos** [comment]
Totally possible with jackson, I think.

http://stackoverflow.com/questions/25185545/jackson-object-mapper-annotations-to-deserialize-a-inner-collection

**Comment by djKianoosh** [comment]
I see that, but I think in at least one scenario I have, I would like to completely ignore the overall response and just grab a portion of the json. So to continue the example above, just get the list of "likes" and produce a `List<Like>` (or even `Set<Like>` or simply `List<String>`).

**Comment by dewos** [comment]
Ah ok, now I understand. It is called "dot notation", something like this:

```java
JSONArray array = jsonResponse.getBody().getObject().getJSONArray("user.foo.likes");

```
I could do that, but you need to stress @thefosk @shashiranjan84 for an approval first. Good luck about that :)

**Comment by djKianoosh** [comment]
Correct, but with the extra capability of mapping it to a user provided class/collection. Something like `ArrayList<Like>` or `TreeSet<Like>`

**Comment by djKianoosh** [comment]
@thefosk & @shashiranjan84  What do you think of this request? It would take this library to another level IMHO :)

**Comment by shashiranjan84** [comment]
Sorry guys lately we all running so busy. Will try to have a look over the weekend. Appreciate  all your help.

**Comment by shashiranjan84** [comment]
@djKianoosh @dewos seems like it would be a great feature to add. Feel free to send a PR.

**Comment by froginvasion** [comment]
@djKianoosh @shashiranjan84 
This might be possible with using the TypeReference trick jackson & others use to get the type of the collection you want and cast it. Question is how you will handle independence of any parsing library.

**Comment by djKianoosh** [comment]
I ran into this library recently which might be a nice integration:
https://github.com/jayway/JsonPath

**Comment by djKianoosh** [comment]
@froginvasion what is the "TypeReference" trick in Jackson that you mention?

**Comment by froginvasion** [comment]
@djKianoosh sorry I didn't see your comment before now.

When you use jackson, and you provide a class, then this will work fine for everything that has a class. But as soon that you want to map to a class that can take type parameters, this approach won't work anymore.

However, in Jackson, there is something called TypeReference. If you implement this interface, and give it the type you want to map, then you can also map to those generic classes.

A typical example is for instance:
`List<Person> persons = new ObjectMapper().readValue(source, new TypeReference<List<Person>>(){}`

Note the extra curly braces, you're creating an anonymous class that implements TypeReference.



On a more technical note: 
this is because Java uses type erasure (unlike some other languages). And by using this TypeReference trick, Jackson can do the cast for you, rather than doing the unchecked cast yourself.

**Comment by kdekooter** [comment]
@mlippens what would be the datatype of `source`?

**Comment by ryber** [comment]
The 2.0 line does have support to pass generic types to the object mapper which should work to let folks do whatever they want with Jackson. The asJson() methods are supposed to be pretty lightweight and just json, not a whole object mapping thing like asObject is.

There are also other new custom mapper methods which should meet the needs.

changing asJson() to be some other library would be a big breaking change to everyone using the current implementation, so we shouldn't replace it at this time.
